[package]
name = "wish"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-std = { version = "1.13.0", features = ["attributes"] }
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
mlua = { version = "0.10.3", features = ["luajit", "error-send", "vendored"] }
nix = { version = "0.29.0", features = ["process", "signal", "socket", "uio"] }
paste = "1.0.15"
